### ISSUE TITLE
头痛根本就启动不起来

### ISSUE THREAD

**Issue by linux52** [Jamling/hexo-theme-nova#17]
root@hexo:~/hexo# hexo s

/root/hexo/node_modules/hexo-filter-highlight/filter.js:50
        label += `[${title}](${url})`;
                 ^
ERROR Plugin load failed: hexo-filter-highlight
SyntaxError: Unexpected token ILLEGAL
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/root/hexo/node_modules/hexo/lib/hexo/index.js:213:21)
    at /root/hexo/node_modules/hexo-filter-highlight/index.js:3:52
    at /root/hexo/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:431:57)
    at Promise._settlePromiseFromHandler (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:522:17)
    at Promise._settlePromise (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at /root/hexo/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /root/hexo/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
ERROR Plugin load failed: hexo-generator-github
AssertionError: urllib-sync need node version 0.11.13+
    at Object.<anonymous> (/root/hexo/node_modules/hexo-generator-github/node_modules/urllib-sync/index.js:19:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/root/hexo/node_modules/hexo-generator-github/lib/helper.js:8:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (/root/hexo/node_modules/hexo/lib/hexo/index.js:213:21)
    at /root/hexo/node_modules/hexo-generator-github/index.js:3:10
    at /root/hexo/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Promise._fulfill (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:636:18)
    at Promise._resolveCallback (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:431:57)
INFO  i18n not config in _config.yml, use default config!
Please visit https://github.com/Jamling/hexo-generator-i18n for more information
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop

**Comment by Jamling** [comment]
你的node.js版本可能太低了
