### ISSUE TITLE
Unhandled rejection TypeError

### ISSUE THREAD

**Issue by jakeywu** [Jamling/hexo-theme-nova#19]
Unhandled rejection TypeError: self.url_for_lang is not a function
    at link (/usr/app/lotusPond/themes/nova/scripts/list_archives.js:71:17)
    at Object.<anonymous> (/usr/app/lotusPond/themes/nova/scripts/list_archives.js:82:74)
    at wrapper (/usr/app/lotusPond/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at Object.eval [as tpl] (eval at precompile (/usr/app/lotusPond/node_modules/swig/lib/swig.js:498:13), <anonymous>:7:143)
    at compiled (/usr/app/lotusPond/node_modules/swig/lib/swig.js:619:18)
    at Theme._View.View._compiledSync (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/usr/app/lotusPond/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at wrapper (/usr/app/lotusPond/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at Object.eval [as tpl] (eval at precompile (/usr/app/lotusPond/node_modules/swig/lib/swig.js:498:13), <anonymous>:15:119)
    at compiled (/usr/app/lotusPond/node_modules/swig/lib/swig.js:619:18)
    at Theme._View.View._compiled (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:29:15)
    at /usr/app/lotusPond/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/usr/app/lotusPond/node_modules/bluebird/js/release/util.js:16:23)
    at /usr/app/lotusPond/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/usr/app/lotusPond/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: this.get_langs is not a function
    at Object.<anonymous> (/usr/app/lotusPond/themes/nova/scripts/helpers.js:423:24)
    at wrapper (/usr/app/lotusPond/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at Object.eval [as tpl] (eval at precompile (/usr/app/lotusPond/node_modules/swig/lib/swig.js:498:13), <anonymous>:6:123)
    at compiled (/usr/app/lotusPond/node_modules/swig/lib/swig.js:619:18)
    at Theme._View.View._compiledSync (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/usr/app/lotusPond/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at wrapper (/usr/app/lotusPond/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at precompile (/usr/app/lotusPond/node_modules/swig/lib/swig.js:498:13), <anonymous>:47:119)
    at Object.exports.each (/usr/app/lotusPond/node_modules/swig/lib/utils.js:45:11)
    at eval (eval at precompile (/usr/app/lotusPond/node_modules/swig/lib/swig.js:498:13), <anonymous>:14:10)
    at Object.eval [as tpl] (eval at precompile (/usr/app/lotusPond/node_modules/swig/lib/swig.js:498:13), <anonymous>:59:3)
    at compiled (/usr/app/lotusPond/node_modules/swig/lib/swig.js:619:18)
    at Theme._View.View._compiledSync (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/usr/app/lotusPond/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at wrapper (/usr/app/lotusPond/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at Object.eval [as tpl] (eval at precompile (/usr/app/lotusPond/node_modules/swig/lib/swig.js:498:13), <anonymous>:11:119)
    at compiled (/usr/app/lotusPond/node_modules/swig/lib/swig.js:619:18)
    at Theme._View.View._compiled (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/usr/app/lotusPond/node_modules/hexo/lib/theme/view.js:29:15)
    at /usr/app/lotusPond/node_modules/hexo/lib/hexo/index.js:387:25

**Comment by Jamling** [comment]
Did you installed [hexo-generator-i18n](https://github.com/Jamling/hexo-generator-i18n) plugin?
url_for_lang is a helper of it.

**Comment by jakeywu** [comment]
thanks and how to update you theme be easily?

**Comment by Jamling** [comment]
@jakeywu cd  to themes/nova dir
`git pull origin master` to update from latest master
if conflict (you make some change)
```
git stash
git pull origin master
git stash pop
```
