### ISSUE TITLE
生成静态页面失败，有两个文件load不进来

### ISSUE THREAD

**Issue by elkan1788** [Jamling/hexo-theme-nova#24]
尝试使用LZ的主题，但是很不幸的是，在生成静态代码时便报错了，有两个文件找不到，异常信息如下：

```
ERROR Script load failed: themes/nova/scripts/helpers.js
Error: Cannot find module '../../../node_modules/hexo/node_modules/lodash'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/hexo/lib/hexo/index.js:216:21)
    at /Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/themes/nova/scripts/helpers.js:4:9
    at /Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
ERROR Script load failed: themes/nova/scripts/project.js
Error: Cannot find module '../../../node_modules/hexo/node_modules/lodash'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/hexo/lib/hexo/index.js:216:21)
    at /Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/themes/nova/scripts/project.js:4:9
    at /Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/hexo/lib/hexo/index.js:232:12
    at tryCatcher (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/promise.js:638:18)
    at /Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/bluebird/js/release/nodeback.js:42:21
    at /Users/senhui.li/CodeSpaces/GithubRepos/hexo-blog/node_modules/graceful-fs/graceful-fs.js:78:16
    at tryToString (fs.js:449:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:436:12)
```
使用的环境如下：

```
hexo: 3.3.6
hexo-cli: 1.0.2
os: Darwin 16.5.0 darwin x64
http_parser: 2.7.0
node: 7.10.0
v8: 5.5.372.43
uv: 1.11.0
zlib: 1.2.11
ares: 1.10.1-DEV
modules: 51
openssl: 1.0.2k
icu: 58.2
unicode: 9.0
cldr: 30.0.3
tz: 2016j
```

请教一下该如何操作，谢谢。

**Comment by elkan1788** [comment]
抱歉，已参考旧的issue解决
