### ISSUE TITLE
启动报错 Unhandled rejection TypeError: Cannot read property 'virtual' of undefined，能帮忙看看么

### ISSUE THREAD

**Issue by lshaolin** [Jamling/hexo-theme-nova#27]
Hexo version: 4.0.0

```powershell
Unhandled rejection TypeError: Cannot read property 'virtual' of undefined
    at Object.<anonymous> (E:\Workspace\My\blog\themes\nova\scripts\helpers.js:403:15)
    at Object.eval [as tpl] (eval at precompile (E:\Workspace\My\blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:11:156)
    at compiled (E:\Workspace\My\blog\node_modules\swig-templates\lib\swig.js:664:18)
    at Theme._View.View._compiledSync (E:\Workspace\My\blog\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (E:\Workspace\My\blog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (E:\Workspace\My\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (eval at precompile (E:\Workspace\My\blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:18:119)
    at Object.exports.each (E:\Workspace\My\blog\node_modules\swig-templates\lib\utils.js:45:11)
    at eval (eval at precompile (E:\Workspace\My\blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:11:10)
    at Object.eval [as tpl] (eval at precompile (E:\Workspace\My\blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:26:3)
    at compiled (E:\Workspace\My\blog\node_modules\swig-templates\lib\swig.js:664:18)
    at Theme._View.View._compiledSync (E:\Workspace\My\blog\node_modules\hexo\lib\theme\view.js:119:22)
    at Theme._View.View.View.renderSync (E:\Workspace\My\blog\node_modules\hexo\lib\theme\view.js:48:23)
    at Object.partial (E:\Workspace\My\blog\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at Object.eval [as tpl] (eval at precompile (E:\Workspace\My\blog\node_modules\swig-templates\lib\swig.js:537:13), <anonymous>:27:119)
    at compiled (E:\Workspace\My\blog\node_modules\swig-templates\lib\swig.js:664:18)
    at Theme._View.View._compiled (E:\Workspace\My\blog\node_modules\hexo\lib\theme\view.js:123:48)
    at Theme._View.View.View.render (E:\Workspace\My\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\Workspace\My\blog\node_modules\hexo\lib\hexo\index.js:365:21
    at tryCatcher (E:\Workspace\My\blog\node_modules\bluebird\js\release\util.js:16:23)
    at E:\Workspace\My\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (E:\Workspace\My\blog\node_modules\hexo\lib\hexo\router.js:123:3)


```

**Comment by Jamling** [comment]
没测试过hexo 4.0.0，hexo 4.x与3.x应该不兼容，你可以换个3.x的hexo版本试试看，nova主题兼容到hexo 3.9.x

**Comment by lshaolin** [comment]
![image](https://user-images.githubusercontent.com/12904465/69850263-df21b780-12b9-11ea-95de-5c8e4e3c0486.png)

注释掉了这些代码，可以运行了，不知道这个函数是干什么的？我注释掉这些并不影响tag的显示

**Comment by Jamling** [comment]
这段代码是用来处理国际化的，用于生成多语言站点

**Comment by lshaolin** [comment]
好的，谢谢！
